### ISSUE TITLE
URL RegExp missing pages

### ISSUE THREAD

**Issue by oschwald** [jasonphanley/nytimes-single-page-articles#1]
I noticed a small bug in this script.  Your URL regexp does not match this URL: http://www.nytimes.com/2010/05/15/your-money/15money.html.  Looking at the regular expression, it appears that the hyphen in "your-money" is the problem.  The expression needs something more than "\w" such as "[\w-]".

**Comment by jasonphanley** [comment]
Thanks for the report. I've fixed this in version 3.
